In [2]:
import cv2
import numpy as np

# Load our image
image = cv2.imread('bunchofshapes.jpg')
cv2.imshow('0 - Original Image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
height,width = image.shape[0],image.shape[1]
blank_image = np.zeros((height,width,3))

In [4]:
orginal_image = image
# Grayscale our image
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

In [5]:
edged = cv2.Canny(gray,50,200)
cv2.imshow('Canny edges Image', edged)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# Find contours and print how many were found
contours, hierarchy = cv2.findContours(edged,cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
print("Number of contours",len(contours))

Number of contours 4


In [7]:
#Draw all contours over blank image
cv2.drawContours(blank_image, contours, -1,(0,255,0),3)
cv2.imshow('Contours over blank image', blank_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#Draw all contours
cv2.drawContours(image, contours, -1,(0,255,0),3)
cv2.imshow('Contours over edged image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#PREVIOUS
import cv2
import numpy as np

# Load our image
image = cv2.imread('bunchofshapes.jpg')
cv2.imshow('0 - Original Image', image)
cv2.waitKey(0)

# Create a black image with same dimensions as our loaded image
blank_image = np.zeros((image.shape[0], image.shape[1], 3))

# Create a copy of our original image
orginal_image = image

# Grayscale our image
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Find Canny edges
edged = cv2.Canny(gray, 50, 200)
cv2.imshow('1 - Canny Edges', edged)
cv2.waitKey(0)

# Find contours and print how many were found
contours, hierarchy = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
print ("Number of contours found = ", len(contours))

#Draw all contours
cv2.drawContours(blank_image, contours, -1, (0,255,0), 3)
cv2.imshow('2 - All Contours over blank image', blank_image)
cv2.waitKey(0)

# Draw all contours over blank image
cv2.drawContours(image, contours, -1, (0,255,0), 3)
cv2.imshow('3 - All Contours', image)
cv2.waitKey(0)

cv2.destroyAllWindows()

Number of contours found =  4


In [10]:
contours

[array([[[817, 370]],
 
        [[816, 371]],
 
        [[815, 371]],
 
        ...,
 
        [[820, 370]],
 
        [[819, 370]],
 
        [[818, 370]]], dtype=int32),
 array([[[596, 345]],
 
        [[596, 346]],
 
        [[595, 347]],
 
        ...,
 
        [[599, 346]],
 
        [[598, 345]],
 
        [[597, 345]]], dtype=int32),
 array([[[1262,  258]],
 
        [[1261,  259]],
 
        [[1260,  259]],
 
        ...,
 
        [[1265,  258]],
 
        [[1264,  258]],
 
        [[1263,  258]]], dtype=int32),
 array([[[135, 245]],
 
        [[135, 246]],
 
        [[134, 247]],
 
        ...,
 
        [[138, 245]],
 
        [[137, 245]],
 
        [[136, 245]]], dtype=int32)]

In [11]:
#Sorting contours by area
import cv2
import numpy as np


# Function we'll use to display contour area
def get_contours_areas(contours):
    all_areas = []
    for cnt in contours:
        area = cv2.contourArea(cnt)
        all_areas.append(area)
    return all_areas

#Load our image
image = cv2.imread('bunchofshapes.jpg')
orginal_image = image

# Let's print the areas of the contours before sorting
print("Contor Areas before sorting",get_contours_areas(contours))

# Sort contours large to small
sorted_contours = sorted(contours, key=cv2.contourArea,reverse=True)

print("Contor Areas after sorting",get_contours_areas(sorted_contours))

for c in sorted_contours:
    cv2.drawContours(orginal_image,c,-1,(255,0,0),3)
    cv2.waitKey(0)
    cv2.imshow('Contours by area', orginal_image)
    
cv2.waitKey(0)
cv2.destroyAllWindows()

Contor Areas before sorting [20587.5, 22901.5, 66579.5, 90222.0]
Contor Areas after sorting [90222.0, 66579.5, 22901.5, 20587.5]


In [25]:
import cv2
import numpy

# Functions we'll use for sorting by position

def x_cord_contour(contours):
     #Returns the X cordinate for the contour centroid
        if cv2.contourArea(contours) >10:
            M = cv2.moments(contours)
            return M
        else:
            pass



In [26]:
x_cord_contour(c)

{'m00': 20587.5,
 'm10': 18250924.833333332,
 'm01': 9099782.333333332,
 'm20': 16214606883.25,
 'm11': 8067011518.125,
 'm02': 4057711167.4166665,
 'm30': 14436508422455.451,
 'm21': 7166954589089.566,
 'm12': 3597188928206.5664,
 'm03': 1824964836980.2002,
 'mu20': 35067975.07837677,
 'mu11': 7590.238600730896,
 'mu02': 35559934.190416336,
 'mu30': -11432.6015625,
 'mu21': 353952.1429042816,
 'mu12': 359855.0387878418,
 'mu03': -6583.537353515625,
 'nu20': 0.08273770399700484,
 'nu11': 1.7908046107890125e-05,
 'nu02': 0.0838984088081491,
 'nu30': -1.8799055832427544e-07,
 'nu21': 5.820167929485615e-06,
 'nu12': 5.9172314619470645e-06,
 'nu03': -1.0825557560719243e-07}

In [29]:
import cv2
import numpy

# Functions we'll use for sorting by position

def x_cord_contour(contours):
     #Returns the X cordinate for the contour centroid
        if cv2.contourArea(contours) >10:
            M = cv2.moments(contours)
            return (int(M['m10']/M['m00']))
        else:
            pass



In [42]:
x_cord_contour(c)

280

In [31]:
def label_contour_center(image,c):
    # Places a red circle on the centers of contours
    M = cv2.moments(c)
    cx = int(M['m10'] / M['m00'])
    cy = int(M['m01'] / M['m00'])
    
    # Draw the countour number on the image
    cv2.circle(image,(cx,cy),10,(0,0,255),-1)
    return image

In [32]:
label_contour_center(image,c)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [33]:
# Load our image
image = cv2.imread('bunchofshapes.jpg')
orginal_image = image.copy()

In [37]:
# Computer Center of Mass or centroids and draw them on our image
for (i, c) in enumerate(contours):
    orig = label_contour_center(image,c)
    
cv2.imshow("4 - Contour Centers ", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(i)

3


In [43]:
contours_left_to_right = sorted(contours,key = x_cord_contour, reverse = False)

In [45]:
# Labeling Contours left to right
for (i,c)  in enumerate(contours_left_to_right):
    cv2.drawContours(orginal_image, [c], -1, (0,0,255), 3)  
    M = cv2.moments(c)
    cx = int(M['m10'] / M['m00'])
    cy = int(M['m01'] / M['m00'])
    cv2.putText(orginal_image, str(i+1), (cx, cy), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('6 - Left to Right Contour', orginal_image)
    cv2.waitKey(0)
    (x, y, w, h) = cv2.boundingRect(c)  
    
    # Let's now crop each contour and save these images
    cropped_contour = orginal_image[y:y + h, x:x + w]
    image_name = "output_shape_number_" + str(i+1) + ".jpg"
    print (image_name)
    cv2.imwrite(image_name, cropped_contour)
    
cv2.destroyAllWindows()

output_shape_number_1.jpg
output_shape_number_2.jpg
output_shape_number_3.jpg
output_shape_number_4.jpg
